### ISSUE TITLE
Implement health report landing site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/internet-health-report#31]
Based on design in [these comps](https://redpen.io/p/zsc99c7d5045f3cc30), done in #30. 

Dates: 
July 10 - QA
July 13 - Launch

Site will live on http://internethealthreport.org/ (URL will no longer redirect to https://internethealthreport.org/v01/)

### Pages include:
- **Home:** nav, hero banner, 2 feature boxes, blog features, newsletter signup, footer
- **Blog overview:** featured posts, category filters, search, and all posts with most recent at the top
- **Blog detail:** title, author, share feature, comment and annotating plugins
- **About:** text and timeline
- **Feedback:** iFrame from Coral Project

### Plugins and Features for launch:
- built in Wordpress and easy to update 
- Parent-child themes and set up as a multi-site with current report
- compliant with Web accessibility guidelines
- RSS to be switched on
- responsive layout across devices
- Newsletter signup to integrate with our Salesforce (same functionality to [Report v0.1](https://internethealthreport.org/v01/) but without the country field)
- [wpDiscuz comments plugin:](http://wpdiscuz.com/) for commenting at the bottom of blog posts (same as on [Report v0.1](https://internethealthreport.org/v01/
- [hypothes.is plugin](https://web.hypothes.is/): for annotations and notes (same as on [Report v0.1](https://internethealthreport.org/v01/) but with some improved styling #32)
- Coral Project Feedback form: iFrame on Feedback Page with the a Coral Project form (similar to [Report v0.1](https://internethealthreport.org/v01/your-feedback/))

### Post launch: (once we have sufficient content)
- [WPML translation plugin](https://wpml.org/): integrated localization capabilities eg. ability for users to toggle between languages, and for editors to easily mirror content in multiple languages (same as on [Report v0.1](https://internethealthreport.org/v01/)) (post launch)
- search (privacy sensitive plugin)
- blog categories, search and related posts feature
- archived Reports section on About page

### Assets for dev:
- Mockup comps https://redpen.io/p/zsc99c7d5045f3cc30
- Sketch design file https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLY0RhWC1BMVZNcm8/view?usp=sharing
- Zeplin file: shared through email
- Exported images + icons https://drive.google.com/drive/folders/0B2irLVDJivhLd0FiZnQ1RjBkRmc?usp=sharing
- Copy doc https://docs.google.com/a/mozilla.com/document/d/13m7VdEtDs80rNn6_U07nPsn4iN7zC3rBPvM6O1OkR8o/edit?usp=sharing
- Similar Mozilla sites: https://www.mozilla.org/en-US/internet-health/ and https://network.mofoprod.net/

cc @samanthaburton @Solanasaurus @xmatthewx @hannahkane

**Comment by xmatthewx** [comment]
> built in Wordpress and easy to update (Parent-child themes?)(Set up as a multi-site?)

I think multi-site is critical for ease of maintenance. WP has simplified this set up in recent years.

**Comment by Solanasaurus** [comment]
This list is fabulous!

Multi-site is already set up, so we're talking about a theme that would be entirely independent of https://internethealthreport.org/v01/

A thing to decide with developer is whether to modify an existing pro/commercial theme or develop something custom.

**Comment by kristinashu** [comment]
Mike, Cade and I are meeting tomorrow so they can discuss setup and deployment. 

@Solanasaurus could you please give Mike access to the relevant plugins?

**Comment by kristinashu** [comment]
Or maybe not plugins, but for the Coral feedback form.

**Comment by Solanasaurus** [comment]
Hi Kristina, the Coral feeback form is an embed. So other than the plugins that are already installed, we don't need anything else. I'm scheduling a meeting with Coral to rework the feedback form.

You might ask Cade about the Hypothes.is installation since I'm not sure how that works.

**Comment by kristinashu** [comment]
👏 Mike is in full swing building the site and Cade is working on setting up a new repo and staging environment for Mike https://github.com/MozillaFoundation/mofo-devops/issues/519

**Comment by kristinashu** [comment]
Site is up on [staging](https://healthreport.staging.wpengine.com/) and we are filing QA tickets in the [repo](https://github.com/mozilla/ihr-landing-site/issues).
