### ISSUE TITLE
Images for Indicators blog post

### ISSUE THREAD

**Issue by kristinashu** [mozilla/internet-health-report#36]
@Solanasaurus will be preparing a blog post this week on the Indicators that were identified in the [crowdsourcing process](https://blog.mozilla.org/internetcitizen/2017/05/15/how-would-you-measure-the-health-of-the-internet/). 

I will create an image for the post.

Please add a draft of the post here when you have it, then I can see what sort of graphic will work.

cc @kaodro

**Comment by kristinashu** [comment]
Working with the title "And the Indicators are..." I'm going to try two different directions:
- award show angle: one open envelope with a note card being pulled out of it and then two closed envelopes with question marks on them
- people have spoken angle: lots of speech bubbles with relevant icons in them

I will do this on Mon/Tue next week.

**Comment by Solanasaurus** [comment]
Sounds good for images, thank you! Maybe the speech bubbles are best, since envelopes sometimes connote emails? But maybe paired with the headline the award-angle will be clear! 

Only other idea I have would be something like litmus-test colors or something inspired by the "talking heads" icons on the Consider.it platform.

**Comment by kaodro** [comment]
@kristinashu just a word of "warning": we will need this image in the beginning of next week as we might need to deliver it the emailing team to prepare the emailing mid-next week. We plan to launch and post the blogpost on Aug 9 and to do the emailing the same day.

**Comment by kristinashu** [comment]
Thanks for the heads up, I'll give you the image tomorrow!

**Comment by kaodro** [comment]
Hi @kristinashu we need the image in a format fitting for the blogpost and for the email (square), here is an example of how it will look in the email: https://bug1379679.bmoattachments.org/attachment.cgi?id=8884996
We need the image ideally by tomorrow (Aug 1) and at latest by Wed (Aug 2) cause it needs to be submitted for approval together with the email.  Thanks!

**Comment by kristinashu** [comment]
Ok, do you want any text or button like in the example? Or is just a graphic ok?

**Comment by kristinashu** [comment]
Here it is as just a graphic:
![email-ihr-indicators](https://user-images.githubusercontent.com/1068783/28791016-e25a3afe-75df-11e7-8fa3-7e38ffa9721f.png)

**Comment by kaodro** [comment]
@kristinashu please add the following text: 
Image text: Internet Health Report 2018 – See the Indicators
The link will lead to the blogpost on the new website. We will have to translate this text into FR, ES and DE and it's possible that I will have to ask you to add these 3 versions to the graphic by the end of the week.

For the blogpost graphic we want this one but without any text or buttons.

Nice!

**Comment by kristinashu** [comment]
Ok, here is the image of the email and I will work on the blog post image next.

![ihr-blog-02](https://user-images.githubusercontent.com/1068783/28852082-77a0980a-76db-11e7-9274-707053ea2938.png)

**Comment by kaodro** [comment]
Looks good, thanks! We liked the other colors better but if you think they somehow clash with the text, we are also ok with this one. Thanks!

**Comment by kristinashu** [comment]
How about these colors?
<img width="1201" alt="ihr-blog" src="https://user-images.githubusercontent.com/1068783/28887723-178ee104-7773-11e7-8118-b4a1d8c6b553.png">
![ihr-email](https://user-images.githubusercontent.com/1068783/28887724-1790f2dc-7773-11e7-890a-dd5c083a47b9.png)

**Comment by kaodro** [comment]
Great, we like these colors better, thanks!

**Comment by kaodro** [comment]
@kristinashu will you send me the images in a better quality so I can forward them to Jessilyn for the emailing? Or this is the final version?

**Comment by TheoChevalier** [comment]
Hi,
Here are the French and German translations:

DE: `Statusbericht zur Internetgesundheit 2018 – Die Indikatoren`
FR: `Bulletin de santé d’Internet 2018 — Voici les indicateurs`
ES:  `Informe de Salud de Internet 2018 – Ver los Indicadores`

**Comment by kristinashu** [comment]
@kaodro the square image should be the right resolution for the email (it will appear at smaller dimension in the email than it is in github right now). 

@TheoChevalier thanks for the translations! Do these look correct?
![ihr-email-de](https://user-images.githubusercontent.com/1068783/28984714-2d0ee874-7914-11e7-8b24-0375e04150fe.png)
![ihr-email-fr](https://user-images.githubusercontent.com/1068783/28984728-39e4ce2e-7914-11e7-989d-394518d79127.png)

**Comment by kaodro** [comment]
@kristinashu looks good! I added the Spanish one:

`Informe de Salud de Internet 2018 – Ver los Indicadores`

I see these ones have a bit different colors, is there a reason for it? If not, I think it might be good to keep them the similar.

**Comment by TheoChevalier** [comment]
+1, looks good :) Thanks Kristina

**Comment by kristinashu** [comment]
Excellent, here's Spanish:
![ihr-email-es](https://user-images.githubusercontent.com/1068783/28985505-c5b2897a-7917-11e7-8b28-23846ded1777.png)

**Comment by kaodro** [comment]
@kristinashu my apologies but I changed the text after Solana's feedback (we had two versions). The final version is` Informe de Salud de Internet 2018 – Ver los Indicadores`
Sorry you have to do it again! What about the different colors? Thanks again!

**Comment by kristinashu** [comment]
Ooops, I copies the wrong color version. Here are the images with updated ES text and color:
![ihr-email-de](https://user-images.githubusercontent.com/1068783/28985954-cc3b4640-7919-11e7-8a99-d30a2e86122b.png)
![ihr-email-es](https://user-images.githubusercontent.com/1068783/28985955-cc40a644-7919-11e7-8da1-d6532ff64476.png)
![ihr-email-fr](https://user-images.githubusercontent.com/1068783/28985956-cc43d332-7919-11e7-9556-95a862cae4f0.png)

**Comment by kaodro** [comment]
I have one more ask if you find the time: for an alternative version of the email we would like to try another image size (banner type), like this ( (1200px wide x 660px high):  https://bug1382877.bmoattachments.org/attachment.cgi?id=8890567 (109kB)
A version with and without the text. 
Thanks, @kristinashu !

**Comment by kristinashu** [comment]
Here you go!

![ihr-email-no-text](https://user-images.githubusercontent.com/1068783/29097628-b23804ac-7c4f-11e7-8b7d-2983b35aeb62.png)
![ihr-email-text](https://user-images.githubusercontent.com/1068783/29097627-b2366264-7c4f-11e7-9463-c4f4f5ba7e15.png)

**Comment by kaodro** [comment]
Awesome, thank you!
