### ISSUE TITLE
Image for IHR blog post on project progress - user survey results focus

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#39]
@kristinashu We need a regular blog post image (similar aesthetic to the previous ones) that would illustrate a blog post on our progress towards the next report. We will focus on our insights from user research (survey and 1:1 interviews) so an image around "what people want, what people said" etc. would be cool but feel free to come up with anything creative you think fits.

We need it by Friday, Oct 13 at latest. Thank you!

**Comment by kaodro** [comment]
An update for @kristinashu 

Could you prepare this image in 2 formats:
- usual blogpost banner
- image for emailing, hero template (https://drive.google.com/file/d/0Bzf0O6d7z8GGYXNteVV4SUhzUzQ/view) 

Temporary title for the blog post "How we’re structuring the next Internet Health Report" - might give you additional ideas for the image. We will be talking about the insights from the user research, building in blocks, more shareability and more data (and no chatbots:). Thanks!

**Comment by kristinashu** [comment]
Thanks @kaodro! Do you have a draft of this blog post that I could see?

**Comment by kaodro** [comment]
We are planning to have a draft tomorrow.

**Comment by kristinashu** [comment]
@kaodro I'm wonder if it should be about (A) the title "How we’re structuring the next Internet Health Report" so about "planning and structure" or (B) about "what people want, what people said" so about "users and feedback"?

**Comment by kaodro** [comment]
Hi Kristina,
I have the blogpost ready, I will share the doc with you now, you can have a look what it is about. It is more "How we are structuring the next report" and that it is based on what people said. Link coming your way now.

**Comment by kristinashu** [comment]
Excellent, thanks! Here's the image. It should work for both the blog and email.

![ihr-structure](https://user-images.githubusercontent.com/1068783/31566043-d396260e-b01d-11e7-84ae-0754ed34f010.png)

**Comment by kaodro** [comment]
Thank you! It is nice minimalistic. We were just wondering here if you could make the shapes maybe look a bit less "Clippy"-like? It reminded us of these times. But if you have no time for that, it's OK like this! Thanks!

**Comment by kristinashu** [comment]
Haha ok, how about this?

![ihr-socialmedia-02](https://user-images.githubusercontent.com/1068783/31629699-42917b56-b269-11e7-99cb-97656eab38c1.png)

**Comment by kaodro** [comment]
We take it!

**Comment by kristinashu** [comment]
Excellent!
