### ISSUE TITLE
Mozfest IHR Research Hub banner design (6 banners + 4 pointer posters)

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#40]
@kristinashu 
Here is our plan for Mozfest: [Internet Research Hub](https://github.com/MozillaFoundation/mozfest-program-2017/issues/618#issuecomment-327451193
) 
We need to design:

- 2 banners with  
1) facts around Internet Health 
2) explanation what the Internet Health Report  
 
- 2 banners  with
1) with template schedules for recommended research-related sessions from Mozfest (empty schedule: space for time, day, session title and place)
2) template schedule for hub sessions schedule with spaces for people to sign-up for empty spots (time, day, session title)

- 1 banner to hang on the balcony (E.g. big letters “Internet Reearch Hub, powered by Internet Health Report”

- 4 different pointer posters: we want to hand little posters around Mozfest that will point to the Internet Research Hub. The posters should have an example of a data point 

Design ideas/suggestions: https://docs.google.com/document/d/1xuyPYEyv9ACUsBjKS0ArRUp6HzqMyU230hsU2sjGNFg/edit

Deadline for this: week before Mozfest weekend (Monday, Oct 23) but let's start earlier, asap so we can iterate on the design, if needed. All will be printed on design school printers on site, requierements will be delivered soon by a student but I believe you worked with them last year.

**Comment by kristinashu** [comment]
Hey, @kaodro when will you have copy for this?

**Comment by kaodro** [comment]
Will try on Friday or Monday latest but feel free to suggest copy if you have any ideas or use lorem ipsum. Banner 3,4,5 are more or less ready (just schedule templates and big letters banner - you can shape them as you see fit).

**Comment by kristinashu** [comment]
@kaodro here's an example of the design direction I'll be doing. It combines branding from both IH and MozFest. I'm not too sure about sizing though, do you have a sense of the space and how much room we will have? I'm thinking each banner would be A2?

(ignore the gray background)
<img width="830" alt="screen shot 2017-10-12 at 3 35 13 pm" src="https://user-images.githubusercontent.com/1068783/31522517-fb06d122-af62-11e7-872f-4c7e70ff83c7.png">

**Comment by kaodro** [comment]
I requested the size of the dividing walls where we will hang them, will update as soon as I get an answer. As for the printers I forwarded you an Email from Esme Simcox with the sizes that can be printed on the printers. Regarding the designs: nice and clean. We will maybe want to reuse the banners for other events so we should avoid any clear Mozfest branding but colors are OK. I will get you the copy on Monday! Thaaank you!

**Comment by kaodro** [comment]
@kristinashu Still waiting for the size but in the meantime, I updated the doc with some copy and added one more banner ("Filling research gaps"). Still missing: "Data points pointing people to the Hub" and "Internet Health Facts", will try to provide the copy tomorrow.

**Comment by kristinashu** [comment]
Ok thanks!

**Comment by kristinashu** [comment]
We are up to over 6 banners now. This are a lot of banners! MozFest is very hectic and overwhelming with posters, people and events happening everywhere. We can't expect people to read and participate with all these banners. Can you prioritize them and get rid of a couple? Maybe we can remove "Internet Research Hub Recommends"?

**Comment by kaodro** [comment]
I know this is a lot. The thing is that we want to re-use these for other events where we might use the same concept and choose the banners that fit best (so you are kind of preparing a universal set). 

We need to keep the recommendations cause they are part of the Hub original concept but if I have to prioritize I would de-prioritize "Facts about Internet Health" and "Research gaps" (I can use a flipchart for that). We will have a pretty big space for ourselves and many dividing walls so I wouldn't worry if this is too much but then again, I've never been there.

**Comment by kaodro** [comment]
@kristinashu I have now the size for the dividing walls we will hang the banners onto. A bit bigger than 2m high and 1m 50cm width.
![img_4483](https://user-images.githubusercontent.com/22129061/31768991-070a37e2-b4d2-11e7-8f08-6f626c3e4a0f.JPG) As for what the printer can print you have the email (pretty confusing one) but when looking at the prints from last year, it looks like they fit these dividing walls pretty well:
![print 1](https://user-images.githubusercontent.com/22129061/31769441-e7f68afc-b4d3-11e7-9290-061a962b51ef.jpg)
![print 2](https://user-images.githubusercontent.com/22129061/31769442-e81a1cce-b4d3-11e7-86ab-446f876ebba7.jpg)
I would like to have them exactly as these ones from last year - can you figure out the size based on all this? It's pretty confusing to me tbh but my bet is that the images would need to be all in one file with some white space around them and each of them around 2 m long and approx. 1m 30cm wide. Does this make sense?

As for the small pointer posters they can be much smaller - A3 would do. 

I updated all the copy in the doc, it is ready now.

**Comment by kristinashu** [comment]
Here are the banners: [IHR-mozfest-banners-02.pdf](https://github.com/mozilla/internet-health-report/files/1408455/IHR-mozfest-banners-02.pdf)

I'm not sure about the dimensions but it will be quick and easy to scale them once we are at the venue. We can measure the board and do some quick adjustments. I would also love to test print one of them and adjust font sizes accordingly.

**Comment by kaodro** [comment]
Wow, they look really nice, thanks so much! I am sorry to bug you again but we made small but important adjustments to the copy today, could you correct it in the banners? 
- changed some wording in the IH facts banner and removed the fact about Facebook (very important)
- changed www. in the url into https:// everywhere
- changed wording in the balcony banner (is not part of the pdf)
- re-worded "Research related session at Mozfest" into "MozFest sessions on Internet Research"
- changed the word order for schedules into "Title /Host /Day /Time /Space" and "Title /Host /Day /Time"
- Moved the word "Schedule" into the second line in the IRH schedule.

All changes are in the Copy doc: https://docs.google.com/document/d/1xuyPYEyv9ACUsBjKS0ArRUp6HzqMyU230hsU2sjGNFg/edit#

I didn't realize you were already working on it yesterday and I thought you will see them right away, sorry for that! Thank you in advance for adjusting. <3

**Comment by kristinashu** [comment]
No worries. Could you please check these?
[IHR-MozFest-banners-02.pdf](https://github.com/mozilla/internet-health-report/files/1411543/IHR-MozFest-banners-02.pdf)
[IHR-MozFest-posters-02.pdf](https://github.com/mozilla/internet-health-report/files/1411544/IHR-MozFest-posters-02.pdf)
[IHR-MozFest-sign-02.pdf](https://github.com/mozilla/internet-health-report/files/1411545/IHR-MozFest-sign-02.pdf)

Again, I'm not too sure about sizes so let's see when we get there. See you soon!

**Comment by kaodro** [comment]
Hey Kristina, thanks again! Let's keep in touch, I was planning the printing for Friday morning and have all the coordinates about the print shop etc from the student. I have your number and will text you on Signal, Telegram or Whatsapp:)

I checked the banners and noticed that there is a typo in the "publication about what hurting and what’s helping the Internet." it misses an "s". Should be "publication about what's hurting and what’s helping the Internet." If that is not a typo but some special English way of writing, let me know as I am not native. 

In posters the poster on "52% of all websites are in English, even though only 25% of the global population understands English." has a full stop at the end while other posters don't. Let's remove it or add everywhere to stay consistent (unless again, there is a reason for it).

And lastly: in the balcony banner you left out "brought to you by the Internet Health Report" - you think it doesn't fit or is there no space? No big deal, just wanted to know the reason.

Yeah, see you soon!

**Comment by kristinashu** [comment]
All updated!
[IHR-MozFest-banners-03.pdf](https://github.com/mozilla/internet-health-report/files/1417775/IHR-MozFest-banners-03.pdf)
[IHR-MozFest-posters-03.pdf](https://github.com/mozilla/internet-health-report/files/1417776/IHR-MozFest-posters-03.pdf)
[IHR-MozFest-sign-03.pdf](https://github.com/mozilla/internet-health-report/files/1417777/IHR-MozFest-sign-03.pdf)

**Comment by kristinashu** [comment]
Here are the final files we printed (re-sized)
[A0-banners.pdf](https://github.com/mozilla/internet-health-report/files/1424292/A0-banners.pdf)
[A3-posters.pdf](https://github.com/mozilla/internet-health-report/files/1424293/A3-posters.pdf)
