### ISSUE TITLE
Image for the Internet Research Hub blogpost (Mozfest logo + dinosaur)

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#41]
Dear @kristinashu , 

We need an image for our blog post about Mozfest. It can be something simple: a mix of the logo:
https://drive.google.com/a/mozilla.com/file/d/0B4gJTycPp_1LVl9OX0tlNXNPajQyYXQxVGJ1WjBEQzlGcWtv/view?usp=sharing

with one of the following Mozfest images from 2016:

https://www.flickr.com/photos/biglesp/30568637832/in/photolist-Ni4bAo-MVas7Y-MURq7F-NKcg4a-MURnP4-NzfhAU-Nzfhk3-NKAuxc-NKAubk-MMLNWS-Nzffwo-MMzG1i-NGm6iU-Ni4ruG-Ni4qKq-MMLKfd-NzfdXm-MMzEGX-NKApu6-NKApiK-NBNYSi-Ni4od1-NBNWgX-NGm2cN-MMzyWD-NKAfxP-NGkX6S-MMzwHF-NKAeHc-Nzf4gs-MMzpx8-NzeWGL-NKzXUZ-NKzWNR-Ni41mW-MMzMRr-Nzfm7G-NzfkLS-NzfjPm-NKAwKP-Nzfiww-Nzfg2S-MMLr1C-MMzndD-MUy9hj-MUxUjQ-MUfb6e-MUxfLU-MUxeuq-NSpv66

https://www.flickr.com/photos/sixteenmilesofstring/30391470520/in/photolist-NiAen3-MZ94RH-NXfjjp-NXfmwF-NXfgdV-NXf7NZ-JimyFf-MMDNr7-Nz8BTA-NGenr9-MMDNbY-NhWrzf-Nz96g1-Nirs3w-NBGKyr-NKuphz-MMDNgY-MZ978B-Nisneb-MN8vkN-MN6baB-MKhHW8-NGK72S-KKjLKW-JY2C8w-KUARyk-NitBw7-JDwd3z-MFAtb4-NzupMD-Ngc63A-Qv9PmQ-QRcN6u-W7qJXo-KMRfkH-Ktu1KW-KMR1eB-Vc5dNa-TrH518-MMDMZW-MMtAY6-U6bBZQ-MMEnV1-KRPDTu-GLhER3-NKtPoH-FZb8E8-GWj298-NxvqyP-JYgrAa

We would also like to add a dinosaur element, if possible and if it fits (we will have inflatable dinosaurs  in the hub). It can also be only the logo with the dinosaur holding a banner with "The Internet Research Hub" or sth similar. 

Up to your creativity!

We need it in the format: for the blog banner

Thank you and ask me if anything is unclear! We need this pretty fast, possibly end of this week (Oct 13) Thanks!

**Comment by kristinashu** [comment]
@kaodro to make it more official looking I've used the MozFest 2017 branding. 

Here is a version without text for the blog:
![ihr-mozfest-blog](https://user-images.githubusercontent.com/1068783/31507919-490109e2-af31-11e7-9476-80e49b544e39.png)

Also another version with text for social media, in case you need it:
![ihr-mozfest-text](https://user-images.githubusercontent.com/1068783/31508063-c2ff1c2a-af31-11e7-9b96-e1d891551d10.png)

**Comment by kaodro** [comment]
Hi Kristina,

Cool! Looks very nice. Would it be also possible to do one version with a small coffee and cookie part (we will hold a "Research and coffee grinder" at the beginning of the festival) and one with a little dinosaur? I know it might sound silly but it fits to our plans at mozfest and I couls use it to illustrate our sessions in the Mozfest program. Thanks so much!

The images for the Mozfest guidebook should measure 640 pixels wide by 240 pixels tall.

**Comment by kristinashu** [comment]
I'm confused about which which visuals and sizes you need? Do you need blog post size + MozFest guidebook size for both Research and coffee grinder + something with the Dinosaur?

**Comment by kaodro** [comment]
Yes, both of them are for the Mozfest guidebook - dinasaur and coffee. The one above is for the blogpost. If the dinosaur one will be great, you can also do it in the blogpost size:) Thanks!

**Comment by kristinashu** [comment]
Here are the coffee and dino images at 640 x 240px:

<img width="641" alt="ihr-mozfest-coffee" src="https://user-images.githubusercontent.com/1068783/31677448-ae751524-b31f-11e7-8c10-a640e312f3c3.png">
<img width="641" alt="ihr-mozfest-dino" src="https://user-images.githubusercontent.com/1068783/31677449-ae95a514-b31f-11e7-90a6-00151e5b0b3e.png">

And here's another generic IH hub image that is a little more in line with the direction where going, in case you need it:

<img width="1201" alt="ihr-mozfest-hub" src="https://user-images.githubusercontent.com/1068783/31677450-aea7eecc-b31f-11e7-93d7-67a463e6e336.png">

**Comment by kaodro** [comment]
Wonderful, love the t-rex! One last (not essential) ask: can you add the phrase "Internet Research Hub" to the banners with dinos and coffee?It will help us establish the name of the Hub if people see it above the session. Thanks a million!

**Comment by kristinashu** [comment]
Here you go! 

<img width="641" alt="ihr-mozfest-coffee2" src="https://user-images.githubusercontent.com/1068783/31734908-0a598804-b3f5-11e7-90e2-0e4aecdf6ba0.png">
<img width="641" alt="ihr-mozfest-dino2" src="https://user-images.githubusercontent.com/1068783/31734910-0aade0b6-b3f5-11e7-9059-dfb7db1734b0.png">
