### ISSUE TITLE
Re-size images for the IHR 2018

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#45]
Hi @beccaklam, please re-size the issues to fit the guidelines (attached) and to fit the upload limit of 1MB. 
[IMAGES folder,](https://drive.google.com/drive/folders/1fFkbd6S8s0AVoTznCSWCsxMH_iKkygpJ)
You can ignore the subfolders called "not selected". In case of the [fake news game images](https://drive.google.com/drive/folders/1I2fHZbSw_60VDWw5-m0VyLtOlcXw6XXF), please combine the logo with the image into one image.

A huge thank you! 

The sizes for the images would approximately be: 
- Side image. 340x500 px approx.
- Column-width image. 880x550 px approx.
- Box-width image. 1060x600 px approx.

![imagesizes](https://user-images.githubusercontent.com/22129061/36230561-17b8ad10-11db-11e8-971f-ef36e834da0f.png)

**Comment by beccaklam** [comment]
Hi @kaodro, I've dropped in the resized images back into their original google drive folders save for three images that I really think we should get new images for. The quality for these images is too low and I think it would bring down the quality of the website. I've found alternative photos for each of these authors, would you be able to go about seeing if we could get their permission to use them? I've attached the links here:

- [x] Nathan Matias (_Anonymity Fallacy_, **Digital Inclusion**): https://daviesjackson.wordpress.com/2013/06/23/where-is-he-now-mit-labs-with-j-nathan-matias/

- [x] Ame Elliot (_Design for a more secure Internet_, **Privacy + Security**) : http://igniteberlin.com/2016/08/24/ame-elliott-privacy-and-security-implications-in-ux/

- [ ] Margrete Raaum (_FIRST responders_, **Privacy + Security**): http://universitas.no/feature/58052/cyberforsvaret

**Comment by beccaklam** [comment]
@kaodro Also, I only sized for 1x but to optimize for retina screens you usually need @2x images. Can you ask the design agency if they need @2x images?

**Comment by kaodro** [comment]
I will. As for the images, the one of Amy is the same so just go ahead and grab it. The other two I will have to ask. Thanks so much! @beccaklam

**Comment by kaodro** [comment]
@beccaklam You can also use the picture of Nathan, same photographer and license. Just remove the old one from the folder. Thaanks!

**Comment by beccaklam** [comment]
thanks @kaodro ! I've updated both Ame and Nathan's google drive folders with the new images.

**Comment by kaodro** [comment]
@beccaklam I think we need to use Margerete low-resolution pict, she didn't answer so far.  Meanhwile there is a new one to re-size (just one): https://drive.google.com/drive/u/0/folders/1TbqUj8hsBXcoOJfDjypW5TxuMsBDAcNW
Thank you!

**Comment by kaodro** [comment]
Dear Becca, one more to re-size was added: it is in the "In Brazil, the bot in public interest" folder in the images folder. Thank you!

**Comment by beccaklam** [comment]
@kaodro Done ✅ :)

**Comment by kaodro** [comment]
@beccaklam Margerte sent the same image we had but in better quality (1,4MB), I guess that would work, right? Could you resize and ping me here? Thank you!

**Comment by beccaklam** [comment]
@kaodro Oh this image is *so* much better! Resized ✅ and in the google drive folder!

**Comment by kaodro** [comment]
Hi @beccaklam we have 3 more images to re-size, if you could have a look:

Nathan J. Mathias (a new, better one): https://drive.google.com/drive/folders/1epTuxFuV_fzcjUn0cTKUsZ3g6OplKx1s
Meredith Whihttaker: https://drive.google.com/drive/folders/1qLWjDwGBJnIAMNfe56J45CT2pJzwXAHk
Michael Henretty (a new, better one):  https://drive.google.com/drive/folders/1Nx1Hzx_gNqicS2aTATYEMNWgGNkGlqIv

Thank you!

**Comment by beccaklam** [comment]
✅ all done! @kaodro

**Comment by kaodro** [comment]
I am sorry but there is another one... here: https://drive.google.com/drive/folders/1_caPaiIA3KuIHn5L6f427VxV7wutQz81
thank you again @beccaklam

**Comment by beccaklam** [comment]
Hi @kaodro is there a higher quality or just larger version of this image? It's quite small so enlarging it to fit the sizes we have is making it super blurry.

**Comment by kaodro** [comment]
Unfortunately this is all we've got (it is from this post_ https://cira.ca/sites/default/files/public/mozilla-embed-in-blog_0.png)

**Comment by beccaklam** [comment]
Didn't we have another image for this post? Sorry, the quality is just quite bad and I would say not to use it if you can avoid it.

**Comment by kaodro** [comment]
We can't use the other image cause there is a minor under 13 in it. Can you choose sth else from here: https://www.hivetoronto.org/coding-combat-cyber-bullying/ I clicked through but they are all pretty bad quality. Let me know! @beccaklam

**Comment by beccaklam** [comment]
@kaodro Done ✅ Seemed like the blog post had a larger file for some reason.

**Comment by kaodro** [comment]
@beccaklam one more (the screenshot)...
https://drive.google.com/drive/folders/1SggV2jF50sJqLAsgfYrpWcGJK5j9JS48
Thank you!

**Comment by beccaklam** [comment]
done ✅ @kaodro

**Comment by kaodro** [comment]
Hi @beccaklam me again. Now we have 3 images from Unsplash and we would like to use them to illustrate the spotlight articles:

For Fake news: https://unsplash.com/photos/5KKglNl852A
For Too big tech: https://unsplash.com/photos/mluSdDeOksc
For IoT: https://unsplash.com/photos/yekGLpc3vro

Could you re-size them, too?

Also, I was wondering whether you are able to process them to look like the images in the folder "Processed images" added by Danny from Vizzuality. If you are able, please add the normal one to the regular folders and the processed ones to the folder "processed images" (note that they are all blue there - it is an error Vizzuality is fixing) https://drive.google.com/drive/folders/1VgkfemiuQuhnENgz4sZmW83xCAyNgk7H

The colors are as on the website:
Web literacy: green 
Decentralization: yellow
Privacy:  blue

**Comment by beccaklam** [comment]
Hi @kaodro I resized the spotlight photos and put them in the regular folders. Re: Processing the images, I'm not sure what exactly Danny is doing to the photos so it would actually take me more time to figure that out than for Danny just to do it and it would probably be more consistent. It should be fast for him to do if he already has the process set up.

**Comment by kaodro** [comment]
OK ,sure thing. Thanks, Becca!

**Comment by kaodro** [comment]
Hi @beccaklam 

Some more to re-size, I added some images to the spotlight folders:

https://drive.google.com/drive/folders/1Lg9CZzc9_yJZ111cx3AvmBmq7hhmaPKx (2 new images)
https://drive.google.com/drive/folders/1qNSPO1Hfn4n9m518YxyvXL0i6-BuGKSx (1 new image)
https://drive.google.com/drive/folders/124xETLBlTn4ZOmZElKDs-IDgOymTzin5 (1 new image)

On this occasion, could you also re-size the screenshot for the rural connectivity post you asked for the presentation? I would add it to our card previews afterwards.

Thank you again!

**Comment by beccaklam** [comment]
Resized the images ✅ 
Here is the resized picture for the rural connectivity post, I didn't see a folder for it so here it is:

![rural-connectivity-880x550](https://user-images.githubusercontent.com/20977376/37717327-b0934ea6-2cf6-11e8-8fd5-0eea9e135775.jpg)

**Comment by beccaklam** [comment]
This is done and IHR 2018 successfully launched! 🎉
