### ISSUE TITLE
Install the Talk "moderate via Slack" plugin

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#49]
Hi @cadecairos Andrew recommended installing the 'moderate via Slack' plugin for Talk. Right now it seems to me that we can only see the comments in Slack? Correct me if I'm wrong.

To set that up, you need to activate the plugin on our side (you need to add it to our configuration) and then someone with Slack admin access needs to talk to Talk (Andrew) so they can add the Slack Token key to the standalone Slack handshake application.

Let me know if that will work and as always, thank you!

**Comment by cadecairos** [comment]
This plugin doesn't ship with talk - can you ask Andrew where it can be found?

**Comment by kaodro** [comment]
I answered on Slack since there was a one-use link generated for us by Andrew.

**Comment by cadecairos** [comment]
Thanks @kasia - I was able to get it up and running, and I've disabled the previous plugin that just added new comments to the channel
